name: Docker Deploy

on:
  push:
    tags: ["*.*.*"]

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      git_tag: ${{ steps.git_info.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: set-matrix
        run: |
          JSON=$(cat .github/workflows/registry.json | tr '\n' ' ' | sed 's/ //g')
          echo "::set-output name=matrix::$JSON"

      - id: git_info
        run: |
          tag=$(echo ${{ github.ref }} | rev | cut -d/ -f1 | rev)
          echo "::set-output name=tag::$tag"

  docker:
    runs-on: ubuntu-latest
    needs: [set-matrix]
    strategy:
      matrix:
        registry: ${{fromJSON(needs.set-matrix.outputs.matrix)}}

    env:
      id: ${{ secrets[matrix.registry.id] }}
      token: ${{ secrets[matrix.registry.token] }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into Registry ${{ matrix.registry.name }}
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry.registry }}
          username: ${{ env.id }}
          password: ${{ env.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "hominsu/builder"

      - name: Build and Push ${{ matrix.registry.name }}
        run: >
          REPO=${{ matrix.registry.push_link }}
          VERSION=${{ needs.set-matrix.outputs.git_tag }}
          docker buildx bake --file docker-bake.hcl --push
